name: flutter_eoas
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.6
  web3dart: ^2.7.3
  bip39: ^1.0.6
  ed25519_hd_key: ^2.3.0
  convert: ^3.1.2
  http: ^1.2.2
  qr_flutter: ^4.1.0
  google_sign_in: ^6.2.2

  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
